version: '3.8'
services:
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "logs:1:1,patch-analysis:1:1"
    depends_on:
      - zookeeper
    networks:
      - analyzer-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - analyzer-net

  victoria-metrics:
    image: victoriametrics/victoria-metrics:latest
    ports:
      - "8428:8428"
    networks:
      - analyzer-net

  log-producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    depends_on:
      - kafka
    networks:
      - analyzer-net
    environment:
      - KAFKA_BROKER=kafka:9092

  patch-analyzer:
    build:
      context: .
      dockerfile: Dockerfile.simple_consumer
    depends_on:
      - kafka
      - victoria-metrics
    networks:
      - analyzer-net
    environment:
      - KAFKA_BROKER=kafka:9092
      - PYTHONUNBUFFERED=1

networks:
  analyzer-net:
    driver: bridge
